### ISSUE TITLE
Error Serious 

### ISSUE THREAD

**Issue by ndhung-dev** [phpsandbox/phpsandbox#1]
### **Description of Bug**
<?php
var_dump("ok");

result: 

Fatal error: Uncaught Error: Call to undefined function cdump() in /var/www/home.php:3
Stack trace:
#0 {main}
thrown in /var/www/home.php on line 3

### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|interactive|[tnfr8](https://phpsandbox.io/n/tnfr8)|8.0|

**Comment by prof-anis** [comment]
Hi, kindly follow the issue report template for the repository so we can have a more concise understanding of the issue being reported. Thanks.
