### ISSUE TITLE
Cannot connect to notebook - `sparkling-bird-0oro-wkiyc`

### ISSUE THREAD

**Issue by JohnnyKamigashima** [phpsandbox/phpsandbox#12]
### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**

**Comment by bosunski** [comment]
Hello @jrrhack, I was able to open the notebook: https://phpsandbox.io/n/sparkling-bird-0oro-wkiyc
Please try again to be sure it is all fine.

If you think this issue persists, please feel free to reopen it.
