### ISSUE TITLE
Falla de phpSandbox

### ISSUE THREAD

**Issue by siomy23** [phpsandbox/phpsandbox#14]
### **Description of Bug**
Hola que tal, tengo tiempo que estoy notando que phpSandbox falla muy seguido, espero puedan solucionar el problema pronto. Me quedo atrasada con las tareas por este motivo

### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**

**Comment by bosunski** [comment]
Hola @siomy23 , gracias por tus comentarios. Lamentamos saber que las frecuentes interrupciones afectaron sus asignaciones. Somos conscientes de los problemas y hemos trabajado arduamente para que todo funcione sin problemas. Hicimos algunos cambios recientes y creemos que deberían resolver algunos de los desafíos que tenemos en la plataforma. Si cree que persisten algunos problemas, estaremos encantados de ayudarle en todo lo que podamos.

Mi español puede ser extraño porque usé un traductor.
