### ISSUE TITLE
storage folder is not showing up in File Explorer

### ISSUE THREAD

**Issue by ismoil-nosr** [phpsandbox/phpsandbox#15]
The laravel's `storage` folder not displayed in File Explorer but I can access to it through terminal.

Btw, I'm using latest Firefox

**Comment by bosunski** [comment]
Hello @ismoil-nosr,

Thanks for your feedback.

Currently, we do not synchronize the `storage` folder as part of the content displayed due to the possibility of binary files being stored there. However, we are working on a way to still make this possible.

**Comment by bosunski** [comment]
Hi @ismoil-nosr, we just released some changes that synchronize the storage folder. You should now be able to see it in File Explorer.

I'll be closing this issue to keep things clean. If you think the issue still persists, please feel free to reopen the issue.
