### ISSUE TITLE
Issue in File name

### ISSUE THREAD

**Issue by theshubhampanchal** [phpsandbox/phpsandbox#16]
### **Description of Bug**
File changes on app/Http/Kernal.php is not working.

### **How can we reproduce it?**
1. Create standard notebook 
2. change something In app/Http/Kernal.php 
3. Refresh the whole tab, then changes are not there. 

### **Expected results**
it would save file changes in app/Http/Kernal.php

### **Actual Behavior**
The system generates another file which is app/http/kernal.php
(h is lowercase in Http & k in Kernal)

### **Solution**
Case sensitivity issue

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|laravel|[mlfmj](https://phpsandbox.io/n/mlfmj)|8.0|

**Comment by bosunski** [comment]
Thanks for the feedback @theshubhampanchal. We will take a look into this and get back to you.

**Comment by bosunski** [comment]
@theshubhampanchal, we've been able to reproduce the issue and we're currently working on a fix. We will update you once its deployed.

**Comment by bosunski** [comment]
@theshubhampanchal We've deployed changes that should resolve the problem. If you think the issue persists, kindly reopen this issue.
