### ISSUE TITLE
Cannot connect to notebook - `laravel`

### ISSUE THREAD

**Issue by sakshijainn25** [phpsandbox/phpsandbox#17]
### **Description of Bug**
Connection to notebook failed!

### **How can we reproduce it?**

1. Create standard notebook
2. Click on My Notebooks
3. See an error Connection to notebook failed!

### **Screenshots or Screencast**

![Screenshot (3)](https://user-images.githubusercontent.com/97307481/148584596-284eed60-8c21-4724-a35d-62cf79b4b037.png)

**Comment by Crousem** [comment]
I am seeing this issue when I fork existing notebooks
