### ISSUE TITLE
"Unable to export to GitHub"

### ISSUE THREAD

**Issue by JoshJOkayguy** [phpsandbox/phpsandbox#2]
### **Description of Bug**
Don't think I'm doing anything wrong, if I am then the application isn't telling me. I have a Laravel 8 + PHP 8 application that I'm trying to export to GitHub. Each and every single time I attempt to export to GitHub I get the error specified in the title. Without fail.

### **How can we reproduce it?**

1. Opened GitHub tab, typed in (tried this multiple time with different casing, no special characters, etc...) literally anything for the name
2. Clicked the button to export to GitHub
3. It loaded for a few seconds, then told me on the bottom right that it was "Unable to export to GitHub" (a side note is that I had to refresh the page because the screen was "greyed out" and I couldn't click anywhere).
4. Checking GitHub shows that the repository was created however no files were transferred.

### **Expected results**
A GitHub repository is created and the files from the sandbox are transferred.

**More notes or context or questions**

**Notebook details**
|Laravel 8|[z5wjr](https://phpsandbox.io/n/z5wjr)|8.0|

**Comment by bosunski** [comment]
Hi @JoshJOkayguy, I've been trying to reproduce the issue you encountered. I forked the notebook you provided in the description and was able to export it to [GitHub](https://github.com/bosunski/psb-test-repo). Are there other contexts I need to know to be able to reproduce this?

**Comment by JoshJOkayguy** [comment]
None that I'm aware of. It simply creates the repo then immediately fails, so I'm left with an empty repository. I'm wondering if perhaps there is some authorization issue on my profile regarding a setting or something that could be causing this issue (like permissions related). I'll look around, but other than that the only other thing I can think of is revoking authorization for PHPSandbox from github then signing in again.

**Comment by JoshJOkayguy** [comment]
Okay, looked further and found out something interesting. Here's everything I just tried:

- Logging out and logging back in (had already tried that  before)
- Revoking OAuth authorization for PHPSandbox
- Signing out of PHPSandbox, creating a brand new account (I had previously just authorized with GitHub), forking the notebook, then trying to export. That's the interesting part, it appears as though this is somehow linked to my GitHub account. I have absolutely no idea how or why. I'll keep looking.

**Comment by bosunski** [comment]
Cool! Is your original account on PHPSandbox created using GitHub or Google or Facebook or Username/Password?

**Comment by JoshJOkayguy** [comment]
Original account was created with GitHub, alt was created with un/pass.

**Comment by bosunski** [comment]
Okay. Quite weird, the issue is. I'll keep digging as well.

**Comment by JoshJOkayguy** [comment]
I tried again on a completely different machine with no luck, not sure why I thought that would change anything. Regardless, after searching for quite some time I'm convinced this is an issue on your end.

**Comment by bosunski** [comment]
@JoshJOkayguy , we just deployed a small change of which we think should fix the problem. Kindly try the export again and let see how it goes.

**Comment by JoshJOkayguy** [comment]
Working like a charm, thanks so much for keeping me updated!

**Comment by bosunski** [comment]
> Working like a charm, thanks so much for keeping me updated!

Thanks for your patience and feedback too.
