### ISSUE TITLE
Problem during upload zip file - composer.json is invalid

### ISSUE THREAD

**Issue by kosinski** [phpsandbox/phpsandbox#20]
### **Description of Bug**
Hi, 
during the creation new netbook from zip file, the error "composer.json is invalid" is always displayed.

### **How can we reproduce it?**

- create "standard" notebook
- download as a zip file
- create new netbook from zip file
- upload already created zip file
- error is displayed

### **Expected results**
Already created zip file from netbook is correctly uploaded.

### **Actual Behavior**
Always the same error "composer.json is invalid" 

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|standard|[7wqcv](https://phpsandbox.io/n/7wqcv)|8.1|

**Comment by prof-anis** [comment]
Hi @kosinski , We have investigated this and it has been fixed. Kindly confirm if you no longer experience this on your notebooks. Thanks for dropping your feedback here and I am sorry for the inconvenience this might have caused.
