### ISSUE TITLE
Problem during upload zip file - file size is calculated wrongly

### ISSUE THREAD

**Issue by kosinski** [phpsandbox/phpsandbox#21]
### **Description of Bug**
Hi,
I tried to upload 1 Mb - I got error: "Archive size cannot be more than 10 Mb".
Please check this functionality.

### **How can we reproduce it?**

1. Create standard notebook 
2. Click on upload Zip file
3. Upload file more than 1 Mb but less than 10 Mb
4. See an error "Archive size cannot be more than 10 Mb".

### **Expected results**
File less than 10 Mb are uploaded correctly.

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|standard|[nzitn](https://phpsandbox.io/n/nzitn)|8.1|

**Comment by prof-anis** [comment]
Hi @kosinski , We are currently looking into this and would revert back as soon as we can. Thanks for reporting it here.

**Comment by prof-anis** [comment]
Hi @kosinski , I have attempted to replicate this but I haven't been able to . It seems to work fine here. Can you try this with other zip files and see if they work ?

**Comment by kosinski** [comment]
Hi,

please try with my file which I have attached here.

Regards,
Piotr

**Comment by prof-anis** [comment]
HI @kosinski, we have confirmed this issue and we are working towards resolving it as soon as possible. I would drop an update here once it has been resolved. Thanks and sorry for the inconveniences, this might have caused.

**Comment by prof-anis** [comment]
Hi @kosinski , this issue has now been fixed. Thanks once again. Please try this on your end to see if everything works fine too.
