### ISSUE TITLE
Blank page on Safari

### ISSUE THREAD

**Issue by dawidgora-old-account** [phpsandbox/phpsandbox#22]
### **Description of Bug**
Hi, I tried to visit phpsandbox on Safari (Version 15.4 (17613.1.17.1.13)), but the page is blank (whole white). On Chrome it works well.

**Comment by bosunski** [comment]
Hi @dawidgora, thanks for reporting this. We have confirmed this issue and will revert once we have an update.

**Comment by prof-anis** [comment]
Hi @dawidgora , This issue has now been fixed. Feel free to reopen if you encounter anything related to this again.
