### ISSUE TITLE
Error `503` on page https://phpsandbox.io/

### ISSUE THREAD

**Issue by jamessantiago** [phpsandbox/phpsandbox#23]
### **Description of Bug**

Getting this 503 error banner on the frontpage.  Unable to signin or create notebooks.

![image](https://user-images.githubusercontent.com/1292303/177064129-83573f1c-b210-458c-a14c-7477e83ff463.png)

**Comment by bosunski** [comment]
Hi @jamessantiago , thanks for reporting. Apologies for the disruption. We've been doing some maintenance in the server and we want to make sure that things are not left in inconsistent states that is why we put the server in maintenance mode.
