### ISSUE TITLE
Couldnt use soap

### ISSUE THREAD

**Issue by dsandrade** [phpsandbox/phpsandbox#24]
### **Description of Bug**
I need to test soap, but I had an error to install de package ext-soap.

Info from https://repo.packagist.org: #StandWithUkraine
Using version * for ext-soap
./composer.json has been updated
Running composer update ext-soap
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires PHP extension ext-soap * but it is missing from your system. Install or enable PHP's soap extension.

To enable extensions, verify that they are enabled in your .ini files:
    - 
    - /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-bcmath.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-exif.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pcntl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-pdo_pgsql.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-redis.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-xsl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-soap` to temporarily ignore these required extensions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require ext-soap:*" to figure out if any version is installable, or "composer require ext-soap:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### **How can we reproduce it?**

1. Create standard notebook '...'
2. Click on packages
3. Add package
4. Search for plugin ext-soap and try to install it
5. See an error ...

### **Expected results**
I expected to install the plugin ext-soap

### **Actual Behavior**
The phpsandbox couldn't install ext-soap, so that way we could not test soap codes.

### **Screenshots or Screencast**
![Screenshot from 2022-07-20 17-33-45](https://user-images.githubusercontent.com/26100880/180076475-b186cb6b-ff83-4ad9-8dec-2afa1ea5fcb6.png)

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|standard|[noisy-leaf-ropg-lf00b](https://phpsandbox.io/n/noisy-leaf-ropg-lf00b)|8.1|

**Comment by prof-anis** [comment]
Hi @dsandrade , currently, notebooks do not come with soap extension for PHP installed in them. We have however included this in our next roll-out which should be released soon. You can watch out on our Twitter handle @phpsandboxio or the community discord group [here](https://discord.gg/w46CNFP). Should you also have other extensions you think we should add, please feel free to let us know. thanks.

**Comment by prof-anis** [comment]
HI @dsandrade , our noteebooks now come bundled with soap extension for PHP. Feel free to try it out and let me know if it works fine for your use case. Thanks.
