### ISSUE TITLE
Secrets in Sandbox

### ISSUE THREAD

**Issue by DumbergerL** [phpsandbox/phpsandbox#26]
### **Is your feature request related to a problem? Please describe.**
The current available Environment Variables are readable to the User. They are not usefull to store credentials or an api-key if i want to share my notebook.

### **Describe the solution you'd like**
Provide Secrets as in Github that are encrypted and can't be read by the user after they are stored. Also take care that the log does not contain the secret.

https://docs.github.com/en/actions/security-guides/encrypted-secrets

**Comment by prof-anis** [comment]
Hi @DumbergerL , thanks for dropping this feedback here. We have taken note of it and we would be working on confirming and fixing it as soon as possible. We would keep you updated here on the status of this issue here.
