### ISSUE TITLE
Cannot connect to notebook - `falling-water-1l78-gfnu7`

### ISSUE THREAD

**Issue by bonvivant8** [phpsandbox/phpsandbox#30]
### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|laravel|[gfnu7](https://phpsandbox.io/n/gfnu7)|8.1|

**Comment by prof-anis** [comment]
Hi @bonvivant8 ,  We have confirmed this issue and it is being worked on. Kindly confirm if this issue has been fixed or if you are still experiencing it. Thanks.
