### ISSUE TITLE
Route Problem

### ISSUE THREAD

**Issue by masternetfmoraes** [phpsandbox/phpsandbox#36]
### **Description of Bug**
The problem is  when i try using the route in any place , is redirect  in 
http://127.0.0.1/

This happens in all route in all notebooks , before they works  ok!!

even using 
{{ route('xxxxx') }} 
and in the  web.php
Route::get('xxx',[YourController::class,'Your method'])->name('yournameroute');

He return the same problem:

http://127.0.0.1/yournameroute.

Them same problem occurs when i use  url
{{ url('yournameroute')}}

when i use the ( php artisan route list) he returns all routes as expected

### **How can we reproduce it?**

1. open the notebook
2. in the route file (web.php) put the route.
3. 2. Put in the file address of route.
4. when i click in any link using {{route('yourroutename')  he redirect for http://127.0.0.1/yourroutename.

**Comment by bosunski** [comment]
Hello @masternetfmoraes,

I'm currently looking into this issue. The issue arose because we recently removed Nginx from our containers to optimize resources. 

In the meantime, a workaround is to force your Laravel `app.url` as the root URL.

Something like this:
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facade\URL;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        URL::forceRootUrl(config('app.url'));
    }
}
```

Please let me know if this helps. I will put further update here once the issue is resolved.

**Comment by bosunski** [comment]
@masternetfmoraes we just deployed a change to address this. Please check it to see if it solves the issue.

**Comment by masternetfmoraes** [comment]
Thanks
