### ISSUE TITLE
Cannot connect to notebook - `old-forest-jooo-dvps6`

### ISSUE THREAD

**Issue by rubendn** [phpsandbox/phpsandbox#37]
### **Description of Bug**
Have 2 notebooks and connection to both fails.

### **How can we reproduce it?**

Try to open a notebook

**Comment by prof-anis** [comment]
Hi @rubendn , thanks for sharing this. We are actively looking into this and we would provide an update for you once we have  one. Thank you!

**Comment by rubendn** [comment]
I cleared my cookies and it started working again.
