### ISSUE TITLE
Cannot connect to notebook - `appli-jeux-societe-3s4m9`

### ISSUE THREAD

**Issue by pecatte** [phpsandbox/phpsandbox#38]
### **Description of Bug**

Unable to fetch notebook content

### **How can we reproduce it?**

Open the notebook

### **Expected results**
Open the notebook

### **Actual Behavior**
Not reason

### **Screenshots or Screencast**
![image](https://user-images.githubusercontent.com/10727055/219975543-7a346afa-a498-4fc3-85cf-2c8eb6d3dfd5.png)

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|laravel|[3s4m9](https://phpsandbox.io/n/3s4m9)|8.1|

**Comment by bosunski** [comment]
Closing this since it is fixed.
