### ISSUE TITLE
Cannot connect to notebook - `maroon-roos-tarpals-wqgv2`

### ISSUE THREAD

**Issue by AleshchenkoMaksim** [phpsandbox/phpsandbox#39]
### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|laravel|[wqgv2](https://phpsandbox.io/n/wqgv2)|8.2|

**Comment by bosunski** [comment]
Can you try again now?

**Comment by sirproton** [comment]
this happens too often

**Comment by bosunski** [comment]
Can you provide a URL @sirproton?

**Comment by sirproton** [comment]
https://phpsandbox.io/n/interactive

![Screenshot 2023-07-31 at 7 56 22 PM](https://github.com/phpsandbox/phpsandbox/assets/72990531/546a0573-aa74-4f69-b78d-e5e8321ada06)

**Comment by ronnytorresmtz** [comment]
I have the same problem, sometimes I can connect and sometimes not.... like it is not stable
