### ISSUE TITLE
Cannot connect to notebook - `sd4rn`

### ISSUE THREAD

**Issue by SophaHum** [phpsandbox/phpsandbox#40]
![Screenshot from 2023-10-20 17-03-30](https://github.com/phpsandbox/phpsandbox/assets/65023605/603323b2-3358-4017-8174-ccf3a7e8ba5f)

**Comment by bosunski** [comment]
Hello @SophaHum,

Can you verify that the issue still exists?

**Comment by roman-myspace** [comment]
this issue is still exist 
![image](https://github.com/phpsandbox/phpsandbox/assets/103169678/7d3729ed-addc-41a4-91ed-fd1f72313332)

**Comment by bosunski** [comment]
Hi @roman-myspace ,
Sorry for the inconvenience.

Can you share the link to the affected notebook?

**Comment by SophaHum** [comment]
Sorry I just testing I can't support u
