### ISSUE TITLE
Cannot connect to notebook - `wst5l`

### ISSUE THREAD

**Issue by khaledmo99** [phpsandbox/phpsandbox#41]
### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**
[object Object]

**Comment by bosunski** [comment]
Hello @khaledmo99,

Thanks for reporting this and apologies for the inconvenience. This was due to an issue in the server not resolving your notebook properly. But it's solved now and you should be able to open the notebook successfully.

Feel free to re-open this issue if it persists.
