### ISSUE TITLE
Cannot connect to notebook - `ufo4z`

### ISSUE THREAD

**Issue by Disl3ks1a** [phpsandbox/phpsandbox#42]
### **Description of Bug**
I have just 2 notebooks and
can not initialize any of it

### **How can we reproduce it?**

Please fix the bug. I have a pretty important code there. 

### **Expected results**
Connection to notebooks is restored. 

### **Actual Behavior**
I click on notebook and website says: Unable to initialize notebook. Make sure you are connected to the internet and then retry.

### **Screenshots or Screencast**
![2023-12-02 12-20-27](https://github.com/phpsandbox/phpsandbox/assets/121483623/db9fa08e-b091-4292-adeb-01b67209285d)

**More notes or context or questions**
[object Object]

**Comment by bosunski** [comment]
Hello @Disl3ks1a ,

Sorry for the inconvenience. I'm currently looking into the issue and will update you shortly.

**Comment by bosunski** [comment]
Hi @Disl3ks1a,

The issue has been resolved and your notebook should now load properly. Please feel free to reopen this issue if it persists.
Once again, sorry for the inconvenience, and thank you for reporting it.
