### ISSUE TITLE
Cannot connect to notebook - `yrkua`

### ISSUE THREAD

**Issue by jaylonia03** [phpsandbox/phpsandbox#43]
### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**
[object Object]

**Comment by bosunski** [comment]
Hello @jaylonia03 , 
Thanks for reporting this issue. 

We have deployed some changes that should fix the issue. Please check the notebook and see if it works.
