### ISSUE TITLE
Cannot connect to notebook !

### ISSUE THREAD

**Issue by vidyadheeshp** [phpsandbox/phpsandbox#5]
### **Description of Bug**
Connection to notebook failed!

### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Expected results**
To open the notebook with files cloned from github

### **Actual Behavior**
It says the connection failed due to internet connectivity despite having good internet connectivity.

### **Screenshots or Screencast**
![image](https://user-images.githubusercontent.com/52103828/126856898-69bc6f9a-0f7f-422a-8fd5-0ef7c19cfceb.png)

**More notes or context or questions**

**Comment by bosunski** [comment]
Hi @vidyadheeshp, thanks for reporting this. 
Can you provide the link to the repository you wanted to import from GitHub?

**Comment by bosunski** [comment]
Closing this for now until @vidyadheeshp provides more context. @vidyadheeshp you can re-open this once you have more context.
