### ISSUE TITLE
Cannot connect to notebook - `morning-mouse-95qq-lrse7`

### ISSUE THREAD

**Issue by maaritv** [phpsandbox/phpsandbox#6]
### **Description of Bug**

My other notebooks work, so this error only comes for this one notebook. It worked this morning, but not anymore. It is a code example, which I have not modified for many months. I just added it to my favourite today. 

### **How can we reproduce it?**

1. Go to url: https://phpsandbox.io/n/morning-mouse-95qq-lrse7 with the browser

### **Expected results**
it is a basic PHP web application project using PDO:s that should open in a sandbox. 

### **Actual Behavior**
A clear and concise description of what happened.

Connection to notebook failed -error message in the middle of the screen. 
Sandbox does not open. (I do not see even project files)

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**

	
![phpsandbox-morning-mouse](https://user-images.githubusercontent.com/24761325/133780035-4a5e854b-c575-480a-bb4a-d557f8d9dd73.png)

**Comment by prof-anis** [comment]
Hi @maaritv , we are looking into this issue. It does not seem easily reproducible but we are investigating likely causes. Should you have more information that could help, do not hesistate to share. This issue would be updated as we make progress. Thanks for reporting this!

**Comment by prof-anis** [comment]
This issue would now be closed. Should it still linger, kindly reopen. Thanks.
