### ISSUE TITLE
List of fork urls

### ISSUE THREAD

**Issue by aario-k24** [phpsandbox/phpsandbox#7]
### **Description of Bug**
Hi,
I really need to see a list of fork URLs. So I can click on those forks and see them. Thank.

### **How can we reproduce it?**

1. Create standard notebook 
2. You cannot see where forks are.

### **Expected results**
A list of links to forks. Like:
```
<a href="blahblah"><anonymouse fork 1></a>
<a href="blahblah2"><anonymouse fork 2></a>
<a href="blahblah3">some user's fork</a>
```

### **Actual Behavior**
There is only a number of forks with no ability to click on it.
### **Screenshots or Screencast**
N/A

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|standard|[ivhuw](https://phpsandbox.io/n/kfzteile24-code-challenge-ivhuw)|8.0|

**Comment by prof-anis** [comment]
Hello, this is a feature that is currently not on PHPSandbox however we intend adding it soon as it is in the pipeline already. Kindly follow us on twitter[ @phpsandbox ](https://twitter.com/phpsandboxio) or join the community on [discord](https://discord.gg/w46CNFP)
