### ISSUE TITLE
Cannot open saved notebooks!

### ISSUE THREAD

**Issue by Awilum** [phpsandbox/phpsandbox#8]
I see the list of notebooks in my profile on this page https://phpsandbox.io/notebooks
But when I click on them nothing happens (except css active/hover effect). 

**Expected results**
Notebook should opened.

**Actual Behavior**
Nothing happens.

**Screenshots**
<img width="1275" alt="Screenshot 2021-09-26 at 11 15 24" src="https://user-images.githubusercontent.com/477114/134799614-f54a29d0-85a7-424b-8dec-955360d735a4.png">

**Environment**
OS: macOS Catalina 10.15.7
Browser: Safari 14

**Comment by prof-anis** [comment]
Hi @Awilum , can you still confirm that this still happens ? I have not been able to reproduce it here. To open your notebook, you should click on the notebook name on the card. Should it still linger, you can reopen the issue. Thanks.
