### ISSUE TITLE
Classic Sandbox - 500 - Internal server error - on the old and even newly created Notebook

### ISSUE THREAD

**Issue by elcheco** [phpsandbox/phpsandbox#9]
### **Description of Bug**
Internal server error 500:

Log shows:
[eqwcp] [2021-10-05 06:41:55],283 CRIT Server 'unix_http_server' running without any HTTP authentication checking
[eqwcp] Could not connect to the server.

### **How can we reproduce it?**

1. Create standard notebook '...'
3. See an error ...

### **Actual Behavior**
A clear and concise description of what happened.

### **Screenshots or Screencast**
You can add screenshots or screen records of the issue.

**More notes or context or questions**

**Notebook details**
|Notebook type|URL|PHP version|
|-|-|-|
|standard|[eqwcp](https://phpsandbox.io/n/eqwcp)|8.0|

**Comment by mercyikpe** [comment]
@elcheco I tried recreating this issue but did not experience it. Here is a screenshot of my Standard Notebook preview screen.
Let me know if you are still experiencing this issue. 

![image](https://user-images.githubusercontent.com/29842348/135987889-210dd612-66d2-40d3-a6f9-ccc93cae3355.png)

**Comment by elcheco** [comment]
Hmm, strange. Now both works, but before for about 15 minutes, the code editor worked, just the website not...
Thanks, I'll close it for now and let's see later...
